import numpy as np
import scipy.sparse as sp

try:
    import umap
    UMAP_AVAILABLE = True
except ImportError:
    UMAP_AVAILABLE = False


def calculate_layout(connectivity, n_nodes, params):
    """
    Alternative layout generation pipeline using UMAP.
    
    connectivity: N x 3 NumPy array representing [Source_Index, Target_Index, Score]
    n_nodes: Total number of nodes in the network
    params: Dictionary containing execution parameters
    
    Returns:
        pos (np.ndarray): Final X/Y coordinates
        box_limit (float): Boundary box size
    """
    if not UMAP_AVAILABLE:
        raise ImportError("UMAP library is not installed. Please install 'umap-learn' to use the UMAP layout engine.")
        
    print(f"Running UMAP global layout on {n_nodes} nodes...")
    
    if connectivity.shape[0] == 0:
        # Edge case: No edges at all
        print("Warning: Network has no edges. Generating random layout.")
        box_limit = (np.sqrt(n_nodes) * 2.5 + 5.0) * params.get('BOX_SCALE', 1.0)
        pos = np.random.uniform(-box_limit/2, box_limit/2, (n_nodes, 2)).astype(np.float32)
        return pos, box_limit

    # Extract connectivity data
    sources = connectivity[:, 0].astype(np.int32)
    targets = connectivity[:, 1].astype(np.int32)
    scores = connectivity[:, 2]

    # --- 1. Score-to-Distance Conversion ---
    # UMAP expects distances >= 0. We convert similarities to distances.
    # By subtracting from the max score, high similarities become distances near 0.
    max_score = np.max(scores)
    distances = max_score - scores

    # --- 2. Build Symmetric Sparse Matrix ---
    # UMAP's 'precomputed' metric requires a symmetric distance matrix.
    # We include both (source -> target) and (target -> source).
    row = np.concatenate([sources, targets])
    col = np.concatenate([targets, sources])
    data = np.concatenate([distances, distances])
    
    # We use COO matrix which is efficient for construction.
    # UMAP handles sparse matrices natively.
    sparse_dist = sp.coo_matrix((data, (row, col)), shape=(n_nodes, n_nodes))
    sparse_dist.eliminate_zeros()

    # --- 3. Run UMAP ---
    n_neighbors = params.get('UMAP_NEIGHBORS', 15)
    # Ensure n_neighbors isn't larger than the dataset minus 1
    n_neighbors = min(n_neighbors, n_nodes - 1)
    if n_neighbors < 2:
        n_neighbors = 2
        
    min_dist = params.get('UMAP_MIN_DIST', 0.1)

    print(f"  > Initializing UMAP (neighbors={n_neighbors}, min_dist={min_dist})")
    import warnings
    warnings.filterwarnings('ignore', category=UserWarning, module='umap')
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        reducer = umap.UMAP(
            metric='precomputed',
            n_components=2,
            n_neighbors=n_neighbors,
            min_dist=min_dist,
            init='spectral',
            random_state=42 # fixed seed for reproducible deterministic layouts
        )
        
        final_pos = reducer.fit_transform(sparse_dist).astype(np.float32)

    # --- 4. Scale and Center Output ---
    # UMAP coordinates are often on a relatively small arbitrary scale.
    # We calculate the standard SSN box limit based on node count and scale the result.
    
    # First, center the layout around (0, 0)
    global_min = np.min(final_pos, axis=0)
    global_max = np.max(final_pos, axis=0)
    center = (global_max + global_min) / 2.0
    final_pos -= center

    # Determine the bounding box size generated by UMAP
    ptp = np.ptp(final_pos, axis=0)
    umap_max_spread = max(ptp[0], ptp[1]) + 1e-9  # avoid division by zero

    # Calculate the desired SSN box limit
    # This matches the calculation from the force-directed layout engine
    target_box = (np.sqrt(n_nodes) * 2.5 + 5.0)
    final_box_limit = target_box * params.get('BOX_SCALE', 1.0)
    
    # Scale UMAP coordinates to span roughly 80% of the target box limit
    # This prevents nodes from sitting exactly on the boundary walls
    scale_factor = (final_box_limit * 1.6) / umap_max_spread 
    final_pos *= scale_factor

    print("UMAP layout calculation complete.")
    return final_pos, final_box_limit
