"""
File: Align_Similarity_Matrix.py
===================================
Description:
This script computes an all-vs-all sequence similarity matrix utilizing protein embeddings instead of traditional sequence 
characters. It performs alignment scoring using dynamic programming on distance matrices derived from the embeddings.

Input:
- HDF5 dataset containing sequence embeddings generated by models like ESM (`{SEQUENCE_SET}_{MODEL_NAME}_embeddings.h5`).

Output:
- A network edge HDF5 file containing pairwise combinations (i, j), raw local/global scores, and alignment lengths (`{SEQUENCE_SET}_{MODEL_NAME}_network.h5`).
- (Optional) An HDF5 file containing compressed path strings for global alignment traceback logic (`{SEQUENCE_SET}_{MODEL_NAME}_paths.h5`).

Settings:
- SEQUENCE_SET: The base name of the project.
- MODEL_NAME: The name of the embedding model used.
- GENERATE_PATHS: Boolean to toggle traceback path saving (saves disk space if False).
- BATCH_SIZE: Number of pairs to process before writing to disk (prevents memory overflow).
- WORKERS: Number of multiprocessing workers to use.
- LOCAL_GAP_P: The gap penalty for local alignment (e.g. Smith-Waterman style).
- GLOBAL_GAP_P: The gap penalty for global alignment (e.g. Needleman-Wunsch style).

Algorithm:
1. Loads pairs of embeddings dynamically from the input HDF5 file.
2. Computes a similarity matrix between the two embeddings using PyTorch (L2-normalized cosine distance converted to exponential similarity, followed by Z-score standardization across rows and columns).
3. Evaluates both a Global Alignment (run_global_traceback) and a Local Alignment (run_local_traceback) utilizing Numba compiled JIT functions for speed. 
4. Batches results sequentially into temporary pickle files.
5. Merges all batches into optimized final HDF5 datasets.
"""
# %% Import Necessary Libraries
# Limit threads to prevent CPU thrashing
import os
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import zlib
import pickle
import numpy as np
import torch
import math
import glob
import shutil
import sys
import h5py
import hashlib
from multiprocessing import Pool, set_start_method
from tqdm import tqdm
from numba import jit
import Hardware_Utils

# ==========================================
# CONFIGURATION
# ==========================================
INPUT_HDF5 = None
EDGE_PREFILTERING = False
PREFILTER_STRENGTH = 20
POOLING_METHOD = "max"    # ("mean", "max") - method to pool residue embeddings into sequence vectors
LENGTH_RATIO_POWER = 2.0  # (float) - exponent to scale the sequence length ratio penalty
GENERATE_PATHS = False
WORKERS = 12
LOCAL_GAP_P = -2.0
GLOBAL_GAP_P = 0.0
BATCH_SIZE = 500000

EMBED_DIR = os.path.join("..", "Embeddings")
NETWORK_DIR = os.path.join("..", "Input_Files", "Networks_EValues")
PATH_DIR = os.path.join("..", "Cache_Files", "Global_Path")

# --- JSON Settings Override ---
import json
import ast
import os

# Automatically calculate the root directory of the SSN project for the current PC
# (Assuming utility scripts are located in the /utilities/ folder)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SETTINGS_FILE = os.path.join(PROJECT_ROOT, "Input_Files", "tools_settings.json")

if os.path.exists(SETTINGS_FILE):
    try:
        with open(SETTINGS_FILE, "r") as f:
            all_settings = json.load(f)
            
            # 1. Load GLOBAL directories and convert relative paths to absolute paths
            if "DIRECTORIES" in all_settings:
                for k, v in all_settings["DIRECTORIES"].items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        # Expand relative paths dynamically based on the current PC
                        if not os.path.isabs(str(v)):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, str(v)))
                        globals()[k] = v
                        
            # 2. Load script-specific settings
            script_name = os.path.basename(__file__)
            if script_name in all_settings:
                user_settings = all_settings[script_name]
                for k, v in user_settings.items():
                    if k in globals() and v is not None and str(v).strip() != "":
                        orig = globals()[k]
                        
                        # Type casting to match the original Python variable type
                        if isinstance(orig, int) and not isinstance(orig, bool):
                            try: v = int(v)
                            except: pass
                        elif isinstance(orig, float):
                            try: v = float(v)
                            except: pass
                        elif isinstance(orig, list):
                            try: v = ast.literal_eval(v) if isinstance(v, str) else v
                            except: pass
                        elif orig is None:
                            if v == "None": v = None
                            elif str(v).replace('.', '', 1).isdigit():
                                v = float(v) if '.' in str(v) else int(v)
                                
                        # Convert any script-specific directory paths to absolute paths
                        if isinstance(v, str) and k.endswith("_DIR") and not os.path.isabs(v):
                            v = os.path.normpath(os.path.join(PROJECT_ROOT, v))
                            
                        globals()[k] = v
    except Exception as e:
        print(f"Failed to load user settings: {e}")

# --- PATH INFERENCE ---
_filename = os.path.basename(INPUT_HDF5)
_base_name = _filename.replace("_embeddings.h5", "").replace(".h5", "")

import re
MODEL_NAME = "unknown"
SEQUENCE_SET = _base_name

match = re.search(r"^(.*)_\[(.*)\]_embeddings\.h5$", _filename)
if match:
    SEQUENCE_SET = match.group(1)
    MODEL_NAME = match.group(2)

FULL_INPUT_HDF5 = os.path.join(EMBED_DIR, INPUT_HDF5)
RESULTS_DIR = os.path.join(NETWORK_DIR, f"{SEQUENCE_SET}_[{MODEL_NAME}]_network_temp") 
FINAL_OUTPUT_NET = os.path.join(NETWORK_DIR, f"{SEQUENCE_SET}_[{MODEL_NAME}]_network.h5") 
FINAL_OUTPUT_PATHS = os.path.join(PATH_DIR, f"{SEQUENCE_SET}_[{MODEL_NAME}]_paths.h5")
        
# %% =======================================
# KERNELS
# ==========================================
def calculate_file_hash(file_path):
    """
    Computes the MD5 checksum of a file in chunks to verify consistency.
    """
    hasher = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            hasher.update(chunk)
    return hasher.hexdigest()

def compute_score_matrix_torch(emb_i, emb_j, device):
    t_i = torch.as_tensor(emb_i, device=device, dtype=torch.float32)
    t_j = torch.as_tensor(emb_j, device=device, dtype=torch.float32)
    t_i_norm = torch.nn.functional.normalize(t_i, p=2, dim=-1)
    t_j_norm = torch.nn.functional.normalize(t_j, p=2, dim=-1)
    cos_sim = torch.mm(t_i_norm, t_j_norm.T)
    dist_mat = 1.0 - cos_sim
    sim_mat = torch.exp(-dist_mat)
    
    epsilon = 1e-8
    row_mean = sim_mat.mean(dim=1, keepdim=True)
    row_std = sim_mat.std(dim=1, keepdim=True)
    col_mean = sim_mat.mean(dim=0, keepdim=True)
    col_std = sim_mat.std(dim=0, keepdim=True)
    
    z_r = (sim_mat - row_mean) / (row_std + epsilon)
    z_c = (sim_mat - col_mean) / (col_std + epsilon)
    final_score = (z_r + z_c) / 2.0
    
    return final_score.to(dtype=torch.float32, device="cpu").numpy()

@jit(nopython=True, fastmath=True)
def run_global_traceback(score_matrix, gap_p):
    N, M = score_matrix.shape
    dp = np.zeros((N + 1, M + 1), dtype=np.float32)
    pointer = np.zeros((N + 1, M + 1), dtype=np.int8)

    for c in range(1, M + 1): dp[0, c] = c * gap_p; pointer[0, c] = 3
    for r in range(1, N + 1): dp[r, 0] = r * gap_p; pointer[r, 0] = 2
    pointer[0, 0] = 0

    for i in range(1, N + 1):
        for j in range(1, M + 1):
            match = dp[i-1, j-1] + score_matrix[i-1, j-1]
            delete = dp[i-1, j] + gap_p
            insert = dp[i, j-1] + gap_p
            
            best = match; ptr = 1
            if delete > best: best = delete; ptr = 2
            if insert > best: best = insert; ptr = 3
            
            dp[i, j] = best
            pointer[i, j] = ptr

    max_score = dp[N, M]
    path_buffer = np.zeros(N + M, dtype=np.int8)
    k = 0
    i, j = N, M
    while i > 0 or j > 0:
        p = pointer[i, j]
        path_buffer[k] = p
        k += 1
        if p == 1: i -= 1; j -= 1
        elif p == 2: i -= 1
        elif p == 3: j -= 1
        else: break 

    return max_score, k, path_buffer[:k]

@jit(nopython=True, fastmath=True)
def run_local_traceback(score_matrix, gap_p):
    N, M = score_matrix.shape
    dp = np.zeros((N + 1, M + 1), dtype=np.float32)
    pointer = np.zeros((N + 1, M + 1), dtype=np.int8)
    
    max_score = 0.0
    max_i, max_j = 0, 0
    
    for i in range(1, N + 1):
        for j in range(1, M + 1):
            match = dp[i-1, j-1] + score_matrix[i-1, j-1]
            delete = dp[i-1, j] + gap_p
            insert = dp[i, j-1] + gap_p
            
            best = 0.0; ptr = 0
            if match > best: best = match; ptr = 1
            if delete > best: best = delete; ptr = 2
            if insert > best: best = insert; ptr = 3
            
            dp[i, j] = best
            pointer[i, j] = ptr
            
            if best > max_score:
                max_score = best
                max_i = i
                max_j = j
                
    align_len = 0
    curr_i, curr_j = max_i, max_j
    while curr_i > 0 and curr_j > 0:
        if dp[curr_i, curr_j] == 0: break 
        p = pointer[curr_i, curr_j]
        if p == 0: break
        align_len += 1
        if p == 1: curr_i -= 1; curr_j -= 1
        elif p == 2: curr_i -= 1
        elif p == 3: curr_j -= 1
        else: break
            
    return max_score, align_len

@jit(nopython=True)
def pack_path_2bit(path_arr):
    n = len(path_arr)
    n_bytes = (n + 3) // 4
    out = np.zeros(n_bytes, dtype=np.uint8)
    for i in range(n_bytes):
        val = 0
        for b in range(4):
            idx = i * 4 + b
            if idx < n: val |= (path_arr[idx] << (b * 2))
        out[i] = val
    return out

# %% =======================================
# HDF5 WORKER INITIALIZATION
# ==========================================
worker_hf = None

def init_worker(h5_path):
    global worker_hf
    worker_hf = h5py.File(h5_path, "r", libver='latest', swmr=True)

# %% =======================================
# HYBRID WORKER - Reverted to individual pairs
# ==========================================
def calculate_hybrid_data(args):
    idx_i, idx_j, header_i, header_j, generate_paths = args
    global worker_hf
    
    device = Hardware_Utils.get_optimal_device()
    
    # 0. Fetch embeddings dynamically from disk
    emb_i = worker_hf["embeddings"][header_i][:]
    emb_j = worker_hf["embeddings"][header_j][:]
    
    # 1. Compute Base Matrix
    matrix = compute_score_matrix_torch(emb_i, emb_j, device)
    
    # 2. GLOBAL PASS
    # Even if paths are disabled, we must run the traceback to get the global g_raw and g_len scores
    g_raw, g_len, path_array = run_global_traceback(matrix, GLOBAL_GAP_P)
    
    # Skip packing and zlib overhead if we don't need paths
    c_path = b""
    if generate_paths:
        packed_path = pack_path_2bit(path_array)
        c_path = zlib.compress(packed_path.tobytes())
    
    # 3. LOCAL PASS
    matrix -= 2.0   
    l_raw, l_len = run_local_traceback(matrix, LOCAL_GAP_P)

    return (idx_i, idx_j, l_raw, l_len, g_raw, g_len, c_path)

# %% =======================================
# PROCESSING & MERGE
# ==========================================
def process_batch(batch_tasks, batch_id, workers, input_h5, embedding_checksum):
    output_filename = os.path.join(RESULTS_DIR, f"batch_{batch_id:05d}.h5")
    results = []
    
    with Pool(processes=workers, initializer=init_worker, initargs=(input_h5,)) as pool:
        iterator = pool.imap_unordered(calculate_hybrid_data, batch_tasks, chunksize=10)
        for res in tqdm(iterator, total=len(batch_tasks), desc=f"  Batch {batch_id}", leave=False):
            results.append(res)
            
    # Save as uncompressed HDF5 for easy access
    rows_i = [r[0] for r in results]
    rows_j = [r[1] for r in results]
    l_scores = [r[2] for r in results]
    l_lens = [r[3] for r in results]
    g_scores = [r[4] for r in results]
    g_lens = [r[5] for r in results]
    
    with h5py.File(output_filename, "w") as hf:
        if embedding_checksum is not None:
            hf.attrs["embedding_checksum"] = embedding_checksum
            
        hf.create_dataset("i", data=np.array(rows_i, dtype=np.uint32))
        hf.create_dataset("j", data=np.array(rows_j, dtype=np.uint32))
        hf.create_dataset("l_score", data=np.array(l_scores, dtype=np.float32))
        hf.create_dataset("l_len", data=np.array(l_lens, dtype=np.uint16))
        hf.create_dataset("g_score", data=np.array(g_scores, dtype=np.float32))
        hf.create_dataset("g_len", data=np.array(g_lens, dtype=np.uint16))
        if GENERATE_PATHS:
            edges_paths = [r[6] for r in results]
            dt_vlen = h5py.vlen_dtype(np.uint8)
            np_paths = np.empty(len(edges_paths), dtype=object)
            for idx, p in enumerate(edges_paths):
                np_paths[idx] = np.frombuffer(p, dtype=np.uint8)
            hf.create_dataset("paths", data=np_paths, dtype=dt_vlen)

def scan_existing_batches(n, current_checksum, computed_mask):
    if not os.path.exists(RESULTS_DIR):
        os.makedirs(RESULTS_DIR, exist_ok=True)
        return
    
    batch_files = glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5"))
    for bf in batch_files:
        try:
            with h5py.File(bf, "r") as hf:
                cached_checksum = hf.attrs.get("embedding_checksum")
                if isinstance(cached_checksum, bytes):
                    cached_checksum = cached_checksum.decode('utf-8')
                if cached_checksum != current_checksum:
                    print(f"⚠️ Checksum mismatch in {bf}! Deleting mismatched cache file...")
                    hf.close()
                    try:
                        os.remove(bf)
                    except Exception as err:
                        print(f"Error removing mismatched file {bf}: {err}")
                    continue
                
                # Check for completeness of the batch file
                required_keys = ["i", "j", "l_score", "l_len", "g_score", "g_len"]
                if not all(k in hf for k in required_keys):
                    print(f"⚠️ Batch file {bf} is missing required datasets. Deleting corrupted cache...")
                    hf.close()
                    try:
                        os.remove(bf)
                    except:
                        pass
                    continue
                
                # Check for matching dataset lengths
                len_i = len(hf["i"])
                lengths_match = True
                for k in ["j", "l_score", "l_len", "g_score", "g_len"]:
                    if len(hf[k]) != len_i:
                        lengths_match = False
                        break
                if not lengths_match:
                    print(f"⚠️ Batch file {bf} has mismatched dataset lengths. Deleting corrupted cache...")
                    hf.close()
                    try:
                        os.remove(bf)
                    except:
                        pass
                    continue
                
                arr_i = hf["i"][:]
                arr_j = hf["j"][:]
                computed_mask[arr_i, arr_j] = True
                computed_mask[arr_j, arr_i] = True
        except Exception as e:
            print(f"Warning: Could not read batch file {bf}: {e}. Deleting corrupted cache file...")
            try:
                os.remove(bf)
            except Exception as err:
                print(f"Error removing corrupted file {bf}: {err}")

def compile_final_output(headers, seq_lens, required_mask, n):
    print(f"\n--- Compiling Final HDF5 Output (Deduplicated) ---")
    
    num_seqs = len(headers)
    idx_dtype = np.uint16 if num_seqs <= 65535 else np.uint32
    
    batch_files = sorted(glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5")))
    
    # We use a 2D mask to track which pairs are successfully written to avoid duplicates
    compiled_mask = np.zeros((n, n), dtype=bool)
    
    # First Pass: Count the total number of unique, valid edges to write
    total_edges = 0
    for bf in tqdm(batch_files, desc="Counting unique edges"):
        try:
            with h5py.File(bf, "r") as hf:
                arr_i = hf["i"][:]
                arr_j = hf["j"][:]
                
                # Filter out elements that do not pass pre-filtering
                if required_mask is not None:
                    valid_mask = required_mask[arr_i, arr_j]
                    arr_i = arr_i[valid_mask]
                    arr_j = arr_j[valid_mask]
                
                # Find which ones are not yet compiled
                uncompiled = ~compiled_mask[arr_i, arr_j]
                unique_i = arr_i[uncompiled]
                unique_j = arr_j[uncompiled]
                
                # Mark as compiled in the first pass
                compiled_mask[unique_i, unique_j] = True
                compiled_mask[unique_j, unique_i] = True
                total_edges += len(unique_i)
        except Exception as e:
            print(f"Warning: Error reading {bf} during counting: {e}")
            
    print(f"Saving Combined Scores to {FINAL_OUTPUT_NET} (Total unique edges: {total_edges})...")
    os.makedirs(os.path.dirname(FINAL_OUTPUT_NET), exist_ok=True)
    
    # Reset compiled_mask for the actual write pass
    compiled_mask.fill(False)
    
    with h5py.File(FINAL_OUTPUT_NET, "w") as hf_out:
        dt_str = h5py.string_dtype(encoding='utf-8')
        hf_out.create_dataset("headers", data=np.array(headers, dtype=object), dtype=dt_str)
        hf_out.create_dataset("seq_lens", data=np.array(seq_lens, dtype=np.uint16))
        
        # Pre-allocate datasets
        hf_out.create_dataset("i", shape=(total_edges,), dtype=idx_dtype)
        hf_out.create_dataset("j", shape=(total_edges,), dtype=idx_dtype)
        hf_out.create_dataset("l_score", shape=(total_edges,), dtype=np.float32)
        hf_out.create_dataset("l_len", shape=(total_edges,), dtype=np.uint16)
        hf_out.create_dataset("g_score", shape=(total_edges,), dtype=np.float32)
        hf_out.create_dataset("g_len", shape=(total_edges,), dtype=np.uint16)
        
        paths_exist = False
        if len(batch_files) > 0:
            with h5py.File(batch_files[0], "r") as hf_in:
                if "paths" in hf_in:
                    paths_exist = True
                    
        hf_p_out = None
        if GENERATE_PATHS and paths_exist:
            print(f"Saving Global Traceback Paths to {FINAL_OUTPUT_PATHS}...")
            os.makedirs(os.path.dirname(FINAL_OUTPUT_PATHS), exist_ok=True)
            hf_p_out = h5py.File(FINAL_OUTPUT_PATHS, "w")
            hf_p_out.create_dataset("headers", data=np.array(headers, dtype=object), dtype=dt_str)
            dt_vlen = h5py.vlen_dtype(np.uint8)
            hf_p_out.create_dataset("paths", shape=(total_edges,), dtype=dt_vlen)
            
        curr_idx = 0
        for bf in tqdm(batch_files, desc="Merging batches"):
            try:
                with h5py.File(bf, "r") as hf_in:
                    arr_i = hf_in["i"][:]
                    arr_j = hf_in["j"][:]
                    
                    uncompiled = ~compiled_mask[arr_i, arr_j]
                    if required_mask is not None:
                        uncompiled &= required_mask[arr_i, arr_j]
                        
                    n_write = np.sum(uncompiled)
                    if n_write == 0:
                        continue
                        
                    end_idx = curr_idx + n_write
                    
                    hf_out["i"][curr_idx:end_idx] = arr_i[uncompiled]
                    hf_out["j"][curr_idx:end_idx] = arr_j[uncompiled]
                    hf_out["l_score"][curr_idx:end_idx] = hf_in["l_score"][:][uncompiled]
                    hf_out["l_len"][curr_idx:end_idx] = hf_in["l_len"][:][uncompiled]
                    hf_out["g_score"][curr_idx:end_idx] = hf_in["g_score"][:][uncompiled]
                    hf_out["g_len"][curr_idx:end_idx] = hf_in["g_len"][:][uncompiled]
                    
                    if hf_p_out is not None and "paths" in hf_in:
                        hf_p_out["paths"][curr_idx:end_idx] = hf_in["paths"][:][uncompiled]
                        
                    # Mark as compiled
                    compiled_mask[arr_i[uncompiled], arr_j[uncompiled]] = True
                    compiled_mask[arr_j[uncompiled], arr_i[uncompiled]] = True
                    
                    curr_idx = end_idx
            except Exception as e:
                print(f"Warning: Error merging batch {bf}: {e}")
                
        if hf_p_out is not None:
            hf_p_out.close()
            
    print("✅ Compilation complete!")

# %% =======================================
# MAIN
# ==========================================
def run_job_distributor():
    if os.path.exists(FINAL_OUTPUT_NET) and (not GENERATE_PATHS or os.path.exists(FINAL_OUTPUT_PATHS)):
        print("✅ Job already done."); return

    try: set_start_method('spawn')
    except RuntimeError: pass

    print(f"Loading Metadata from {FULL_INPUT_HDF5}...")
    if not os.path.exists(FULL_INPUT_HDF5): print("Embeddings file not found."); return

    with h5py.File(FULL_INPUT_HDF5, "r") as hf:
        raw_headers = hf["headers"][:]
        headers = [h.decode('utf-8') if isinstance(h, bytes) else h for h in raw_headers]
        
        print("Pre-calculating sequence lengths...")
        seq_lens = []
        safe_headers = []
        for h in tqdm(headers, desc="Reading lengths"):
            safe_h = h.replace("/", "_").replace("\\", "_")
            safe_headers.append(safe_h)
            seq_lens.append(hf["embeddings"][safe_h].shape[0])

    n = len(headers)
    total_pairs = (n * (n - 1)) // 2
    
    # Prefiltering logic
    required_mask = None
    if EDGE_PREFILTERING and PREFILTER_STRENGTH > 0 and n >= 2:
        print(f"\n--- 🛠️ Edge Prefiltering: Calculating {POOLING_METHOD} Pooled Length-Adjusted Similarities ---")
        mean_embs = []
        with h5py.File(FULL_INPUT_HDF5, "r") as hf:
            for h in tqdm(safe_headers, desc=f"Pooling Embeddings ({POOLING_METHOD})"):
                emb = hf["embeddings"][h][:]
                if POOLING_METHOD == "max":
                    pooled = np.max(emb, axis=0)
                else:
                    pooled = np.mean(emb, axis=0)
                mean_embs.append(pooled)
        mean_embs = np.array(mean_embs, dtype=np.float32)
        
        # Calculate all-vs-all cosine similarities on CPU
        norms = np.linalg.norm(mean_embs, axis=1, keepdims=True)
        norms = np.where(norms == 0, 1e-8, norms)
        norm_embs = mean_embs / norms
        cos_sim = np.dot(norm_embs, norm_embs.T)
        
        # Apply sequence length ratio adjustment
        seq_lens_array = np.array(seq_lens, dtype=np.int32)
        lens_col = seq_lens_array[:, np.newaxis]
        lens_row = seq_lens_array[np.newaxis, :]
        min_lens = np.minimum(lens_col, lens_row)
        max_lens = np.maximum(lens_col, lens_row)
        max_lens = np.maximum(max_lens, 1)
        length_ratio_mat = min_lens / max_lens
        
        if LENGTH_RATIO_POWER != 1.0:
            length_ratio_mat = length_ratio_mat ** LENGTH_RATIO_POWER
            
        cos_sim = cos_sim * length_ratio_mat
        
        # Memory-efficient percentile extraction
        mask = np.triu(np.ones((n, n), dtype=bool), k=1)
        triu_values = cos_sim[mask]
        del mask
        
        threshold = np.percentile(triu_values, PREFILTER_STRENGTH)
        del triu_values
        
        # Get indices of kept pairs
        mask = np.triu(np.ones((n, n), dtype=bool), k=1)
        required_mask = (cos_sim >= threshold) & mask
        del mask, cos_sim
        
        num_kept = np.sum(required_mask)
        print(f"  > Prefilter Strength: {PREFILTER_STRENGTH}%")
        print(f"  > Adjusted Similarity Threshold: {threshold:.6f}")
        print(f"  > Retaining {num_kept} / {total_pairs} pairs ({100.0 * num_kept / total_pairs:.2f}%)")
        print("-----------------------------------------------------------\n")

    # Allocate computed mask
    computed_mask = np.zeros((n, n), dtype=bool)

    # Calculate checksum of the input embedding file to validate cache
    print("Calculating checksum of input embedding file...")
    current_checksum = calculate_file_hash(FULL_INPUT_HDF5)
    print(f"  > Checksum: {current_checksum}")

    # Scan existing batches for already computed pairs
    scan_existing_batches(n, current_checksum, computed_mask)

    # Find the next available batch_id
    existing_batches = glob.glob(os.path.join(glob.escape(RESULTS_DIR), "batch_*.h5"))
    batch_ids = []
    for f in existing_batches:
        base = os.path.basename(f)
        try:
            num = int(base.split("_")[1].split(".")[0])
            batch_ids.append(num)
        except:
            pass
    next_batch_id = max(batch_ids) + 1 if batch_ids else 0

    # Calculate stats
    effective_total_pairs = np.sum(required_mask) if required_mask is not None else total_pairs
    if required_mask is not None:
        num_computed_and_required = np.sum(computed_mask & required_mask) // 2
    else:
        num_computed_and_required = np.sum(computed_mask) // 2

    num_tasks = effective_total_pairs - num_computed_and_required
    print(f"Total Required pairs: {effective_total_pairs}")
    print(f"Already computed pairs: {num_computed_and_required}")
    print(f"Pairs queued for calculation: {num_tasks}")

    # Build queue of missing tasks and process on the fly
    if num_tasks > 0:
        current_batch = []
        batch_id = next_batch_id
        
        batches_to_run = math.ceil(num_tasks / BATCH_SIZE)
        pbar = tqdm(total=batches_to_run, desc="Overall Progress", unit="batch")
        
        for i in range(n):
            cols = np.arange(i + 1, n)
            
            row_computed = computed_mask[i, i+1:]
            if required_mask is not None:
                row_required = required_mask[i, i+1:]
                pending_mask = row_required & (~row_computed)
            else:
                pending_mask = ~row_computed
                
            if not np.any(pending_mask):
                continue
                
            pending_cols = cols[pending_mask]
            for j_val in pending_cols:
                current_batch.append((i, int(j_val), safe_headers[i], safe_headers[j_val], GENERATE_PATHS))
                if len(current_batch) >= BATCH_SIZE:
                    process_batch(current_batch, batch_id, WORKERS, FULL_INPUT_HDF5, current_checksum)
                    batch_id += 1
                    current_batch = []
                    pbar.update(1)

        if len(current_batch) > 0:
            process_batch(current_batch, batch_id, WORKERS, FULL_INPUT_HDF5, current_checksum)
            pbar.update(1)
            
        pbar.close()

    # Compile intermediate HDF5 batches into final output
    compile_final_output(headers, seq_lens, required_mask, n)

if __name__ == "__main__":
    run_job_distributor()